import type { NextConfig } from "next";
import { withSentryConfig } from "@sentry/nextjs";

const nextConfig: NextConfig = {
  // Standalone output for Docker deployment
  output: 'standalone',

  // Image optimization
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
    ],
  },

  // Legacy favicon path for tools like GitHub, OGP scrapers, and old browsers
  // that hardcode /favicon.ico. Our dynamic icon lives at /icon (generated by
  // src/app/icon.tsx) — the rewrite serves it at /favicon.ico too.
  async rewrites() {
    return [
      {
        source: '/favicon.ico',
        destination: '/icon',
      },
    ];
  },
};

export default withSentryConfig(nextConfig, {
  org: "i-creativi-yi",
  project: "webmaster-monitor",
  authToken: process.env.SENTRY_AUTH_TOKEN,
  widenClientFileUpload: true,
  tunnelRoute: "/monitoring",
  silent: !process.env.CI,
});
